Vagrant.configure("2") do |config|
    config.vm.define "testwindows"
    config.vm.box = "win10"
    config.vm.communicator = "winrm"
    config.vm.provision :shell, :path => "bootstrap.ps1"

    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "hyperv" do |h|
        h.enable_virtualization_extensions = true
        h.cpus = 4
        h.maxmemory = 4092
    end
end
