---
- hosts: localhost 
  become: yes
  tasks:
  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present
  
  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add user {{user}}
    user:
      name: "{{user}}"
      shell: /bin/bash
      generate_ssh_key: no
      password: $6$HXvgnNcq9W/jEMsj$JvJy7zb5eOIBFkDkQS1S3UmPTwoWjzbBynSTlBBJ3ADq3Ltb.qJUKjLpBIYB2ftrGhAfWnuZyAN8uxxPHgxBK0
      groups: wheel,admin

  - name: Set up authorized keys for {{user}}
    authorized_key: 
      user: "{{user}}"
      state: present
      key: "{{item}}"
    with_file:
      - /mnt/c/Users/{{user}}/deployments/windeploy/ansible/ssh/id_rsa.pub

  - name: Create the ansible directory
    file:
      path: /etc/ansible/
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Create the ansible certificates directory
    file:
      path: /etc/ansible/certificates
      state: directory
      owner: root
      group: wheel
      mode: 0770

  - name: Install the ansible hosts file
    copy:
      src: /mnt/c/Users/{{user}}/deployments/windeploy/ansible/ansible_hosts
      dest: /etc/ansible/hosts
      owner: root
      group: wheel
      mode: 0640

  - name: Install user settings for {{user}}
    copy:
      src: /mnt/c/Users/{{user}}/deployments/windeploy/ansible/userconfig.yaml
      dest: /etc/ansible/userconfig.yaml
      owner: root
      group: wheel
      mode: 0640

  - name: Install WinRM Public Certificate
    copy:
      src: /mnt/c/Users/{{user}}/deployments/windeploy/ansible/certificates/WinRMCert.pem
      dest: /etc/ansible/certificates/WinRMCert.pem
      owner: root
      group: wheel
      mode: 0640

  - name: Install WinRM Private Certificate
    copy:
      src: /mnt/c/Users/{{user}}/deployments/windeploy/ansible/certificates/WinRMCert.pfx
      dest: /etc/ansible/certificates/WinRMCert.pfx
      owner: root
      group: wheel
      mode: 0640
    register: result

  - name: Convert the WinRM Private Certificate
    command: "openssl pkcs12 -in WinRMCert.pfx -nocerts -nodes -out cert_key.pem -passin pass: -passout pass:"
    when: result.changed
    args:
      chdir: "/etc/ansible/certificates/"

  - name: Set the WinRM Private Certificate permissions
    file:
      path: /etc/ansible/certificates/cert_key.pem
      owner: root
      group: wheel
      mode: 0640

  - name: Install id_rsa for {{user}}
    copy:
      src: /mnt/c/Users/{{user}}/deployments/windeploy/ansible/ssh/id_rsa
      dest: /home/{{user}}/.ssh/id_rsa
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0600

  - name: Create the deployments directory
    file:
      path: /home/{{user}}/deployments
      state: directory
      owner: "{{user}}"
      group: "{{user}}"
      mode: 0755

  - name: Cloning envsetup into {{user}}/deployments
    git:
      repo: '{{EnvsetupRepo}}'
      dest: "/home/{{user}}/deployments/envsetup"
      remote: origin
      version: "{{GitBranch}}"
      accept_hostkey: yes
    become: yes
    become_user: "{{user}}"

  - name: Cloning resrictedenv into {{user}}/deployments
    git:
      repo: 'dreddor@dreddor.net:build/restrictedenv'
      dest: "/home/{{user}}/deployments/restrictedenv"
      remote: origin
      accept_hostkey: yes
    become: yes
    when: UseRestricted=='True'
    become_user: "{{user}}"
