---
- hosts: localhost 
  become: yes
  tasks:
  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present
  
  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Add user dreddor
    user:
      name: dreddor
      shell: /bin/bash
      generate_ssh_key: no
      password: $6$HXvgnNcq9W/jEMsj$JvJy7zb5eOIBFkDkQS1S3UmPTwoWjzbBynSTlBBJ3ADq3Ltb.qJUKjLpBIYB2ftrGhAfWnuZyAN8uxxPHgxBK0
      groups: wheel,admin

  - name: Set up authorized keys for dreddor
    authorized_key: 
      user: dreddor 
      state: present
      key: "{{item}}"
    with_file:
      - /mnt/c/Users/dreddor/deployments/windeploy/ansible/ssh/id_rsa.pub

  - name: Install id_rsa for dreddor
    copy:
      src: /mnt/c/Users/dreddor/deployments/windeploy/ansible/ssh/id_rsa
      dest: /home/dreddor/.ssh/id_rsa
      owner: dreddor
      group: dreddor
      mode: 0600
    
    
